/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlylaptop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Tai
 */
public class Them_hoa_don extends javax.swing.JFrame {
    private String mahd,tensp,loaisp,masp,maadmin,ghichu;
    private int soluong,gia,hoanthanh;
    String ngaylap;
    private Connection con;
    private Connection con1;
    private ResultSet rs;
    private ResultSet rs1;
    private PreparedStatement stmt;
    private PreparedStatement stmt1;
    private Object UbUtil;
    private Object DbUtils;
    private Object UbUtils;
    
    /**
     * Creates new form Them_hoa_don
     */
    public Them_hoa_don() {
        initComponents();
    }
    public void getInfor(){
        
       
        masp = jMSP.getText();
         tensp = jTSP.getText();
          maadmin = jMaAdmin.getText();
           ghichu = jGhiChu.getText();
            mahd = jMaHoaDOn.getText();
             soluong = Integer.parseInt(jSL.getText());
              gia=Integer.parseInt(jGia.getText());
              Date ngaylap = jngaylap.getDate();
              SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss");
              String ngaylap1 = format.format(ngaylap.getTime());
              
//               ngaylap=jDateNL.getDate().toString();
               if(jRadioButton1.isSelected()){
                   hoanthanh= 1;
               }else if(jRadioButton2.isSelected()){
                   hoanthanh=0;
               }else{
                   JOptionPane.showMessageDialog(this,"Mời chọn trạng thái hóa đơn" );
               }
               
        
        try{
             Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://Localhost/shoplaptop", "root", "");
             stmt=con.prepareStatement("INSERT INTO `hoadon`(`mahd`, `maadmin`, `ngaylap`, `ghichu`, `hoanthanh`) values(?,?,?,?,?)");
           stmt.setString(1, mahd);
           stmt.setString(2, maadmin);
           stmt.setString(3,ngaylap1);
           stmt.setString(4, ghichu);
           stmt.setInt(5, hoanthanh);
           
            Class.forName("com.mysql.jdbc.Driver");
           con1 = DriverManager.getConnection("jdbc:mysql://Localhost/shoplaptop", "root", "");
           stmt1=con1.prepareStatement("INSERT INTO `chitiethoadon`(`mahd`, `masp`, `soluong`, `gia`) values(?,?,?,?)");
           stmt1.setString(1, mahd);
           stmt1.setString(2, masp);
           stmt1.setInt(3, soluong );
           stmt1.setInt(4, 200);
           int i=stmt.executeUpdate();
           int j=stmt1.executeUpdate();
           if(i>0&&j>0){
               JOptionPane.showMessageDialog(null, "Đăng Ký Thành Công");
              
               Giaodienhoadon giaodien = new Giaodienhoadon();
                giaodien.setSize(1024, 768);
                giaodien.setLocationRelativeTo(null);
                giaodien.setVisible(true);
               
           }else{
               JOptionPane.showMessageDialog(null, "Đăng Ký Thất Bại");
           } 
           con.close();
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMSP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jGia = new javax.swing.JTextField();
        jMaHoaDOn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMaAdmin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGhiChu = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jngaylap = new com.toedter.calendar.JDateChooser();

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bảng Thêm Hóa Đơn");
        setBackground(new java.awt.Color(102, 102, 255));
        setFocusCycleRoot(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Nhập Thông Tin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 40, 138, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Tên Sản Phẩm:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 140, 17);
        getContentPane().add(jTSP);
        jTSP.setBounds(190, 80, 140, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Mã Sản Phẩm:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 120, 17);
        getContentPane().add(jMSP);
        jMSP.setBounds(190, 120, 140, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Số Lượng:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 80, 17);
        getContentPane().add(jSL);
        jSL.setBounds(190, 160, 140, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Giá của sản phẩm:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 210, 130, 17);
        getContentPane().add(jGia);
        jGia.setBounds(190, 200, 140, 30);
        getContentPane().add(jMaHoaDOn);
        jMaHoaDOn.setBounds(190, 250, 140, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Mã Hóa Đơn:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 257, 88, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Mã Admin:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 310, 80, 17);
        getContentPane().add(jMaAdmin);
        jMaAdmin.setBounds(190, 300, 140, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Ghi Chú:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 390, 60, 17);

        jGhiChu.setColumns(20);
        jGhiChu.setRows(5);
        jScrollPane1.setViewportView(jGhiChu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 370, 230, 90);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Ngày Lập:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 470, 80, 17);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Lập Phiếu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 520, 100, 23);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Hủy");
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 520, 90, 23);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 620, 0, 630);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Hoàn Thành:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 350, 80, 17);

        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(190, 340, 43, 23);

        jRadioButton2.setText("No");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(250, 340, 39, 23);
        getContentPane().add(jngaylap);
        jngaylap.setBounds(190, 470, 133, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getInfor();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Them_hoa_don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Them_hoa_don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Them_hoa_don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Them_hoa_don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Them_hoa_don giaodien = new Them_hoa_don();
               giaodien.setSize(500, 600);
               giaodien.setLocation(250, 150);
               giaodien.setVisible(true);
               
               
//                new Them_hoa_don().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextArea jGhiChu;
    private javax.swing.JTextField jGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMSP;
    private javax.swing.JTextField jMaAdmin;
    private javax.swing.JTextField jMaHoaDOn;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jSL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTSP;
    private com.toedter.calendar.JDateChooser jngaylap;
    // End of variables declaration//GEN-END:variables
}
