/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlylaptop;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import Iteam.set_so_cuatextfile;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tai
 */

public class GiaodienquanlyAdmin extends javax.swing.JFrame {

    private Connection con;
    private ResultSet rs;
    private PreparedStatement stmt;
    private Object UbUtil;
    private Object DbUtils;

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * Creates new form GiaodienquanlyAdmin
     */
    public GiaodienquanlyAdmin() {
        initComponents();
        try {
            con = MySqlConnect.ConnectDb();
        } catch (Exception e) {

        }
        Updata_Table();
    }

    public void Updata_Table() {
        Vector cols = new Vector();
        cols.addElement("Mã Admin");
        cols.addElement("Tên Admin");
        cols.addElement("Năm Sinh");
        cols.addElement("Chứng Minh Thư");
        cols.addElement("Tên Đăng Nhập");
        cols.addElement("Mật Khẩu");
        cols.addElement("Điện Thoại");
        cols.addElement("Địa Chỉ");
        cols.addElement("Giới Tính");
//        
        Vector data = new Vector();

        String sql = "SELECT * FROM `admin`";
//        bang_data.setModel(new DefaultTableModel(data, cols));
        try {
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery();
//           bang_data.setModel(DbUtils.resultSetToTableModel(rs));
            while (rs.next()) {
                Vector user = new Vector();
                user.addElement(rs.getString("maadmin"));
                user.addElement(rs.getString("tenadmin"));
                user.addElement(rs.getDate("ngaysinh"));
                user.addElement(rs.getString("cmnd"));
                user.addElement(rs.getString("tendangnhap"));
                user.addElement(rs.getString("matkhau"));
                user.addElement(rs.getString("dienthoai"));
                user.addElement(rs.getString("diachi"));
                user.addElement(rs.getString("gioitinh"));
                data.add(user);
            }
        } catch (Exception e) {
//           JOptionPane.showMessageDialog(null, cols);
        }
        ds_admin.setModel(new DefaultTableModel(data, cols));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doimatkhau = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        matkhau_hientai = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        matkhau_moi = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        matkhau_moi_xac_nhan = new javax.swing.JPasswordField();
        Doi_mat_khau_nut_cap_nhat = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        thong_bao_mk = new javax.swing.JLabel();
        tro_giup = new javax.swing.JButton();
        thongbao_mat_khau_moi = new javax.swing.JLabel();
        xac_nhan_khongdung = new javax.swing.JLabel();
        matkhau_xac_nhan = new javax.swing.JLabel();
        dialog_hinh_nen = new javax.swing.JLabel();
        buttom_timkiem = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dangky = new javax.swing.JButton();
        nut_cap_nhat = new javax.swing.JButton();
        nut_xoa = new javax.swing.JButton();
        combox = new javax.swing.JComboBox();
        ToolBar_menu = new javax.swing.JToolBar();
        sanpham = new javax.swing.JButton();
        loaisanpham = new javax.swing.JButton();
        Hoadon = new javax.swing.JButton();
        thongke = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        doi_matkhau = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        chua_nhap_ID = new javax.swing.JLabel();
        txt_ngaysinh = new com.toedter.calendar.JDateChooser();
        chua_dien_mat_khau = new javax.swing.JLabel();
        bang_thong_tin = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txt_tenadmin = new javax.swing.JTextField();
        txt_cmt = new javax.swing.JTextField();
        txt_tendangnhap = new javax.swing.JTextField();
        txt_matkhau = new javax.swing.JPasswordField();
        txt_dienthoai = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        txt_timkiem = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ds_admin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        hinh_nen = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        doimatkhau.getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Mật Khẩu");
        doimatkhau.getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 20, 90, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Mật khẩu hiện tại:");
        doimatkhau.getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 30, 120, 14);

        matkhau_hientai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        matkhau_hientai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        doimatkhau.getContentPane().add(matkhau_hientai);
        matkhau_hientai.setBounds(270, 70, 160, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Mật khẩu mới:");
        doimatkhau.getContentPane().add(jLabel12);
        jLabel12.setBounds(140, 80, 100, 14);

        matkhau_moi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        matkhau_moi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matkhau_moi.setToolTipText("Mật khẩu từ 6 -> 12 ký tự");
        matkhau_moi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                matkhau_moiFocusLost(evt);
            }
        });
        doimatkhau.getContentPane().add(matkhau_moi);
        matkhau_moi.setBounds(270, 20, 160, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Xác nhận mật khẩu:");
        doimatkhau.getContentPane().add(jLabel13);
        jLabel13.setBounds(140, 140, 120, 14);

        matkhau_moi_xac_nhan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        matkhau_moi_xac_nhan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        doimatkhau.getContentPane().add(matkhau_moi_xac_nhan);
        matkhau_moi_xac_nhan.setBounds(270, 130, 160, 30);

        Doi_mat_khau_nut_cap_nhat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Doi_mat_khau_nut_cap_nhat.setText("Cập nhật");
        Doi_mat_khau_nut_cap_nhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doi_mat_khau_nut_cap_nhatActionPerformed(evt);
            }
        });
        doimatkhau.getContentPane().add(Doi_mat_khau_nut_cap_nhat);
        Doi_mat_khau_nut_cap_nhat.setBounds(210, 200, 100, 23);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Bỏ qua");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        doimatkhau.getContentPane().add(jButton2);
        jButton2.setBounds(350, 200, 80, 23);

        thong_bao_mk.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        thong_bao_mk.setForeground(new java.awt.Color(255, 51, 0));
        doimatkhau.getContentPane().add(thong_bao_mk);
        thong_bao_mk.setBounds(270, 50, 160, 20);

        tro_giup.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tro_giup.setText("Trợ Giúp");
        doimatkhau.getContentPane().add(tro_giup);
        tro_giup.setBounds(0, 200, 81, 40);

        thongbao_mat_khau_moi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        thongbao_mat_khau_moi.setForeground(new java.awt.Color(255, 51, 0));
        doimatkhau.getContentPane().add(thongbao_mat_khau_moi);
        thongbao_mat_khau_moi.setBounds(270, 104, 160, 20);
        doimatkhau.getContentPane().add(xac_nhan_khongdung);
        xac_nhan_khongdung.setBounds(250, 170, 180, 20);
        doimatkhau.getContentPane().add(matkhau_xac_nhan);
        matkhau_xac_nhan.setBounds(270, 164, 170, 20);

        dialog_hinh_nen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dialog/icon_doimatkhau.png"))); // NOI18N
        doimatkhau.getContentPane().add(dialog_hinh_nen);
        dialog_hinh_nen.setBounds(0, 0, 480, 250);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        buttom_timkiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttom_timkiem.setText("Tim Kiem");
        buttom_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttom_timkiemActionPerformed(evt);
            }
        });
        getContentPane().add(buttom_timkiem);
        buttom_timkiem.setBounds(830, 403, 100, 30);

        jButton3.setBackground(new java.awt.Color(188, 54, 23));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Nhập Lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(890, 350, 90, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Trang Quản Trị Tài Khoản Admin");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 60, 380, 40);

        dangky.setBackground(new java.awt.Color(66, 163, 214));
        dangky.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dangky.setForeground(new java.awt.Color(255, 255, 255));
        dangky.setText("Đăng Ký");
        dangky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangkyMouseClicked(evt);
            }
        });
        dangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangkyActionPerformed(evt);
            }
        });
        getContentPane().add(dangky);
        dangky.setBounds(520, 350, 110, 40);

        nut_cap_nhat.setBackground(new java.awt.Color(58, 153, 192));
        nut_cap_nhat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        nut_cap_nhat.setForeground(new java.awt.Color(255, 255, 255));
        nut_cap_nhat.setText("Cập Nhật");
        nut_cap_nhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut_cap_nhatActionPerformed(evt);
            }
        });
        getContentPane().add(nut_cap_nhat);
        nut_cap_nhat.setBounds(650, 350, 110, 40);

        nut_xoa.setBackground(new java.awt.Color(54, 172, 129));
        nut_xoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nut_xoa.setForeground(new java.awt.Color(255, 255, 255));
        nut_xoa.setText("Xóa");
        nut_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut_xoaActionPerformed(evt);
            }
        });
        getContentPane().add(nut_xoa);
        nut_xoa.setBounds(780, 350, 100, 40);

        combox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nu", "Gay", "Less" }));
        getContentPane().add(combox);
        combox.setBounds(660, 300, 140, 40);

        ToolBar_menu.setBorder(null);
        ToolBar_menu.setFloatable(false);
        ToolBar_menu.setRollover(true);
        ToolBar_menu.setMaximumSize(new java.awt.Dimension(2000, 59));
        ToolBar_menu.setMinimumSize(new java.awt.Dimension(2000, 59));
        ToolBar_menu.setPreferredSize(new java.awt.Dimension(2000, 25));

        sanpham.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sanpham.setForeground(new java.awt.Color(255, 255, 255));
        sanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/nho/quanlysanpham-1.png"))); // NOI18N
        sanpham.setText("Sản Phẩm");
        sanpham.setFocusable(false);
        sanpham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sanpham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sanphamMouseClicked(evt);
            }
        });
        ToolBar_menu.add(sanpham);

        loaisanpham.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        loaisanpham.setForeground(new java.awt.Color(255, 255, 255));
        loaisanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/nho/loai-san-pham_1.png"))); // NOI18N
        loaisanpham.setText("Loại Sản Phẩm");
        loaisanpham.setFocusable(false);
        loaisanpham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loaisanpham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        loaisanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loaisanphamMouseClicked(evt);
            }
        });
        ToolBar_menu.add(loaisanpham);

        Hoadon.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Hoadon.setForeground(new java.awt.Color(255, 255, 255));
        Hoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/nho/Hoa_Don_1.png"))); // NOI18N
        Hoadon.setText("Hóa Đơn");
        Hoadon.setFocusable(false);
        Hoadon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Hoadon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Hoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoadonActionPerformed(evt);
            }
        });
        ToolBar_menu.add(Hoadon);

        thongke.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        thongke.setForeground(new java.awt.Color(255, 255, 255));
        thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/nho/thong_ke_1.png"))); // NOI18N
        thongke.setText("Thống Kê");
        thongke.setFocusable(false);
        thongke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thongke.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongkeActionPerformed(evt);
            }
        });
        ToolBar_menu.add(thongke);

        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/nho/quan_ly_1.png"))); // NOI18N
        jButton12.setText("Admin");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar_menu.add(jButton12);

        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/nho/tro_giup_1.png"))); // NOI18N
        jButton13.setText("Trợ Giúp");
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        ToolBar_menu.add(jButton13);

        doi_matkhau.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doi_matkhau.setForeground(new java.awt.Color(255, 255, 255));
        doi_matkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/nho/icon_doi_mat_khau.png"))); // NOI18N
        doi_matkhau.setText("Đổi Mật Khẩu");
        doi_matkhau.setFocusable(false);
        doi_matkhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        doi_matkhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        doi_matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doi_matkhauActionPerformed(evt);
            }
        });
        ToolBar_menu.add(doi_matkhau);

        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/nho/dangsuat.png"))); // NOI18N
        jButton15.setText("Đăng Xuất");
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        ToolBar_menu.add(jButton15);

        jButton16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/nho/iocn_thoat_1.png"))); // NOI18N
        jButton16.setText("Thoát");
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar_menu.add(jButton16);

        getContentPane().add(ToolBar_menu);
        ToolBar_menu.setBounds(0, 0, 2000, 60);

        chua_nhap_ID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chua_nhap_ID.setForeground(new java.awt.Color(255, 0, 51));
        chua_nhap_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(chua_nhap_ID);
        chua_nhap_ID.setBounds(200, 144, 250, 20);

        txt_ngaysinh.setDateFormatString("yyyy-MM-dd");
        txt_ngaysinh.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(txt_ngaysinh);
        txt_ngaysinh.setBounds(150, 225, 340, 40);

        chua_dien_mat_khau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chua_dien_mat_khau.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(chua_dien_mat_khau);
        chua_dien_mat_khau.setBounds(760, 84, 210, 30);

        bang_thong_tin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ho_tro/-anh-nen-dep-99.png"))); // NOI18N
        getContentPane().add(bang_thong_tin);
        bang_thong_tin.setBounds(20, 60, 1070, 390);

        txt_ID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });
        txt_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_IDKeyPressed(evt);
            }
        });
        getContentPane().add(txt_ID);
        txt_ID.setBounds(148, 104, 320, 44);

        txt_tenadmin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_tenadmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_tenadmin);
        txt_tenadmin.setBounds(150, 161, 320, 44);

        txt_cmt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_cmt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_cmt);
        txt_cmt.setBounds(168, 286, 310, 40);

        txt_tendangnhap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_tendangnhap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_tendangnhap);
        txt_tendangnhap.setBounds(171, 340, 310, 50);

        txt_matkhau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_matkhau.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_matkhau);
        txt_matkhau.setBounds(650, 112, 340, 46);

        txt_dienthoai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_dienthoai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_dienthoai);
        txt_dienthoai.setBounds(650, 170, 340, 50);

        txt_diachi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_diachi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_diachi);
        txt_diachi.setBounds(651, 230, 340, 50);

        txt_timkiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_timkiem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_timkiem);
        txt_timkiem.setBounds(91, 399, 750, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        jScrollPane1.setBorder(null);

        ds_admin.setAutoCreateRowSorter(true);
        ds_admin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ds_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ds_admin.setAutoscrolls(false);
        ds_admin.setFocusable(false);
        ds_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds_adminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ds_admin);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 450, 1015, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/chuant.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1040, 60, 120, 600);

        hinh_nen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinh-nen-admin-1.png"))); // NOI18N
        getContentPane().add(hinh_nen);
        hinh_nen.setBounds(-140, -60, 2000, 1500);

        jMenu1.setText("Trang Chủ");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem1.setText("Đăng Xuất");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem2.setText("Thoát");
        jMenu1.add(jMenuItem2);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Sản Phẩm");
        jMenu2.setToolTipText("");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuBar2.add(jMenu2);

        jMenu8.setText("Loại Sản Phẩm");
        jMenu8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu8);

        jMenu4.setText("Hóa Đơn");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        jMenu7.setText("Thống Kê");
        jMenu7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu7);

        jMenu5.setText("Admin");
        jMenu5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem3.setText("Đổi Mật Khẩu");
        jMenu5.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem4.setText("Thêm Tài Khoản");
        jMenu5.add(jMenuItem4);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Trợ Giúp");
        jMenu6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void dangky_tai_khoan() {
        
        String ID = new String(txt_ID.getText());
        if (ID.equals("")) {
            chua_nhap_ID.setText("Bạn chưa nhập ID!");
            txt_ID.requestFocus();
            return;
        }
        String tendangnhap = new String(txt_tendangnhap.getText());
        if (tendangnhap.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền tên đăng nhập");
        }
        String pw = new String(txt_matkhau.getText());
        if (pw.equals("")) {
            chua_dien_mat_khau.setText("Bạn chưa nhập mật khẩu");
            txt_matkhau.requestFocus();
            return;
        }
        
        set_so_cuatextfile nhap = new set_so_cuatextfile();
        if(nhap.checkNum(this.txt_ID.getText())==false){
            JOptionPane.showMessageDialog(null, "ID bạn phải nhập số");
        }
        
        if(nhap.checkNum(this.txt_cmt.getText())==false){
            JOptionPane.showMessageDialog(null, "Chứng minh thư bạn phải nhập số");
        }
        
//        if(nhap.checkNum(this.txt_dienthoai.getText())==false){
//            JOptionPane.showMessageDialog(null, "Số điện thoại bạn phải nhập số");
//        }
        

        String sqlquery = "SELECT `tendangnhap` FROM `admin` WHERE `tendangnhap`=?";
        try {
            stmt = con.prepareStatement(sqlquery);
//        
            stmt.setString(1, txt_tendangnhap.getText());
            rs = stmt.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "tên đăng nhập bị trùng");
                chua_nhap_ID.setText(null);
                chua_dien_mat_khau.setText(null);
            } else {
//                String sqlquery = "SELECT `tendangnhap` FROM `admin` WHERE `tendangnhap`=?";
                stmt = con.prepareStatement(sqlquery = "SELECT `maadmin` FROM `admin` WHERE `maadmin`=?");
                stmt.setString(1, txt_ID.getText());
                rs = stmt.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "ID bị trùng");
//                    chua_dien_mat_khau.setText(null);
//                    chua_nhap_ID.setText(null);
                } else {
                    String sql = "INSERT INTO `admin`(`maadmin`, `tenadmin`, `ngaysinh`, `cmnd`, `tendangnhap`, `matkhau`, `dienthoai`, `diachi`, `gioitinh`) VALUES (?,?,?,?,?,?,?,?,?)";

                    stmt = con.prepareStatement("INSERT INTO `admin`(`maadmin`, `tenadmin`, `ngaysinh`, `cmnd`, `tendangnhap`, `matkhau`, `dienthoai`, `diachi`, `gioitinh`) VALUES (?,?,?,?,?,?,?,?,?)");
                    Class.forName("com.mysql.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://Localhost/quanlysach", "root", "");
                    stmt.setString(1, txt_ID.getText());
                    stmt.setString(2, txt_tenadmin.getText());
                    stmt.setString(3, ((JTextField) txt_ngaysinh.getDateEditor().getUiComponent()).getText());
                    stmt.setString(4, txt_cmt.getText());
                    stmt.setString(5, txt_tendangnhap.getText());
                    stmt.setString(6, txt_matkhau.getText());
                    stmt.setString(7, txt_dienthoai.getText());
                    stmt.setString(8, txt_diachi.getText());
                    stmt.setString(9, combox.getSelectedItem().toString());

                    int i = stmt.executeUpdate();

                    if (i > 0) {
                        JOptionPane.showMessageDialog(null, "Đăng Ký Thành Công");
                        Lam_sach();
                        Updata_Table();
                    } else {
                        JOptionPane.showMessageDialog(null, "Đăng Ký Thất Bại");
                    }

                }

            }
        } catch (Exception e) {
        }
    }


    private void dangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangkyActionPerformed
        dangky_tai_khoan();
    }//GEN-LAST:event_dangkyActionPerformed

    private void dangkyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangkyMouseClicked

    }//GEN-LAST:event_dangkyMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        close();
        GiaoDienAdmin giaodien = new GiaoDienAdmin();
        giaodien.setSize(1024, 768);
        giaodien.setLocationRelativeTo(null);
        giaodien.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        close();
        Tailogin giaodien = new Tailogin();
        giaodien.setSize(1024, 768);
        giaodien.setLocationRelativeTo(null);
        giaodien.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void nut_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_xoaActionPerformed
        // xoa tai khoan
        String sql = "DELETE FROM `admin` WHERE maadmin=?";
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa tài khoản không");
        if (choice == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(txt_ID.getText());
                stmt = con.prepareStatement("DELETE FROM `admin` WHERE maadmin=?");
                stmt.setInt(1, id);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Xóa Thành Công");
                Updata_Table();
                Lam_sach();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Chọn 1 user muốn xóa");
            }
        }
    }//GEN-LAST:event_nut_xoaActionPerformed

    private void nut_cap_nhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_cap_nhatActionPerformed
        String sql = "UPDATE `admin` SET `maadmin`=?,`tenadmin`=?,`ngaysinh`=?,`cmnd`=?,`tendangnhap`=?,`matkhau`=?,`dienthoai`=?,`diachi`=?,`gioitinh`=? WHERE `maadmin`=?";

        try {
            int id = Integer.parseInt(txt_ID.getText());
            stmt = con.prepareStatement("UPDATE `admin` SET `maadmin`=?,`tenadmin`=?,`ngaysinh`=?,`cmnd`=?,`tendangnhap`=?,`matkhau`=?,`dienthoai`=?,`diachi`=?,`gioitinh`=? WHERE `maadmin`=?");
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://Localhost/quanlysach", "root", "");
            stmt.setString(1, txt_ID.getText());
            stmt.setString(2, txt_tenadmin.getText());
            stmt.setString(3, ((JTextField) txt_ngaysinh.getDateEditor().getUiComponent()).getText());
            stmt.setString(4, txt_cmt.getText());
            stmt.setString(5, txt_tendangnhap.getText());
            stmt.setString(6, txt_matkhau.getText());
            stmt.setString(7, txt_dienthoai.getText());
            stmt.setString(8, txt_diachi.getText());
            stmt.setString(9, combox.getSelectedItem().toString());
            stmt.setInt(10, id);
            int i = stmt.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Cập nhật Thành Công");
                Lam_sach();
                Updata_Table();
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật Thất Bại");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Chọn 1 User bạn muốn cập nhật");
        }
    }//GEN-LAST:event_nut_cap_nhatActionPerformed

    private void doi_matkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doi_matkhauActionPerformed
        doimatkhau.setSize(480, 300);
        doimatkhau.setLocationRelativeTo(null);
        doimatkhau.setVisible(true);
//                giaodien.setSize(480, 300);
//                giaodien.setLocationRelativeTo(null);
//                giaodien.setVisible(true);

    }//GEN-LAST:event_doi_matkhauActionPerformed

    public void lamsachdoimatkhau(){
        matkhau_moi.setText(null);
        matkhau_hientai.setText(null);
        thong_bao_mk.setText("");
        thong_bao_mk.setText(null);
        matkhau_xac_nhan.setText("");
        matkhau_moi_xac_nhan.setText(null);
        xac_nhan_khongdung.setText("");
        
        
    }
    
    
    
    private void Doi_mat_khau_nut_cap_nhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doi_mat_khau_nut_cap_nhatActionPerformed

        String pw = new String(matkhau_moi.getPassword());
        if (pw.equals("")) {
            thong_bao_mk.setText("Bạn chưa điền mật khẩu hiện tại");
            matkhau_moi.requestFocus();
            return;
        }

        String pw1 = new String(matkhau_hientai.getPassword());
        if (pw1.equals("")) {
            thongbao_mat_khau_moi.setText("Bạn chưa nhập mật khẩu mới");
            matkhau_hientai.requestFocus();
            return;
        }

        String pw2 = new String(matkhau_moi_xac_nhan.getPassword());
        if (pw2.equals("")) {
            matkhau_xac_nhan.setText("Bạn chưa nhập mật khẩu xác nhận");
            matkhau_moi_xac_nhan.requestFocus();
            return;
        }
        if(!pw1.equals(pw2)){
            xac_nhan_khongdung.setText("Xác nhận mật khẩu không đúng");
             matkhau_moi_xac_nhan.requestFocus();
            return;
        }

        try {
            con = MySqlConnect.ConnectDb();
            stmt = con.prepareStatement("UPDATE `admin` SET `matkhau`=? WHERE `matkhau`=?");
            stmt.setInt(1, Integer.parseInt(matkhau_hientai.getText()));
            stmt.setString(2, matkhau_moi.getText());

            int i = stmt.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Bạn Đã Đổi Mật Khẩu Thành Công");
//                close();
                lamsachdoimatkhau();
                Updata_Table();

            } else {
                JOptionPane.showMessageDialog(null, "Thông tin chưa chính xác");
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Doi_mat_khau_nut_cap_nhatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        matkhau_moi.setText(null);
        matkhau_hientai.setText(null);
        matkhau_moi_xac_nhan.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttom_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttom_timkiemActionPerformed
        String txt_search = txt_timkiem.getText().trim();
        Vector cols = new Vector();
        cols.addElement("Mã Admin");
        cols.addElement("Tên Admin");
        cols.addElement("Năm Sinh");
        cols.addElement("Chứng Minh Thư");
        cols.addElement("Tên Đăng Nhập");
        cols.addElement("Mật Khẩu");
        cols.addElement("Điện Thoại");
        cols.addElement("Địa Chỉ");
        cols.addElement("Giới Tính");

        Vector data_timkiem = new Vector();

        String sql = "SELECT * FROM `admin`";
        try {
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery();
//           bang_data.setModel(DbUtils.resultSetToTableModel(rs));
            while (rs.next()) {
                Vector user = new Vector();
                user.addElement(rs.getString("maadmin"));
                user.addElement(rs.getString("tenadmin"));
                user.addElement(rs.getDate("ngaysinh"));
                user.addElement(rs.getString("cmnd"));
                user.addElement(rs.getString("tendangnhap"));
                user.addElement(rs.getString("matkhau"));
                user.addElement(rs.getString("dienthoai"));
                user.addElement(rs.getString("diachi"));
                user.addElement(rs.getString("gioitinh"));

                if (user.toString().contains(txt_search)) {
                    data_timkiem.addElement(user);
                }
            }
        } catch (Exception e) {
//           JOptionPane.showMessageDialog(null, cols);
        }
        ds_admin.setModel(new DefaultTableModel(data_timkiem, cols));
//       ds_admin.setModel(new DefaultTableModel(null, cols));
    }//GEN-LAST:event_buttom_timkiemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Lam_sach();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ds_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds_adminMouseClicked
        Showdu_lieu_ra_bang();
    }//GEN-LAST:event_ds_adminMouseClicked

    private void txt_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IDKeyPressed
        String sData = this.txt_ID.getText();
        boolean flag = false;

        for (int i = 0; i < sData.length(); i++) {
            if (!Character.isWhitespace(sData.charAt(i))) {
                //JOptionPane.showMessageDialog(null, "Nhap thanh cong");
                flag = true;
                break;
            }
            if (flag = true) {
                System.out.println("Khong dc nhap khoang trang");
            } else {
                System.out.println("Nhap thanh cong");
            }

        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            chua_nhap_ID.setText("nhập ID!");
            txt_ID.requestFocus();
        }
    }//GEN-LAST:event_txt_IDKeyPressed

    private void matkhau_moiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_matkhau_moiFocusLost
        if(new String(matkhau_moi.getPassword()).equals("")){
            thong_bao_mk.setText("Bạn chưa điền mật khẩu hiện tại");
        }
        
    }//GEN-LAST:event_matkhau_moiFocusLost

    private void thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongkeActionPerformed
       close();
        Thongke_chuan thok = new Thongke_chuan();
                thok.setSize(1009, 634);
                thok.setLocationRelativeTo(null);
                thok.setVisible(true);
    }//GEN-LAST:event_thongkeActionPerformed

    private void HoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoadonActionPerformed
        close();
        Giaodienhoadon giaodien = new Giaodienhoadon();
        giaodien.setSize(1024, 768);
     giaodien.setLocationRelativeTo(null);
     giaodien.setVisible(true);
    }//GEN-LAST:event_HoadonActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        close();
        Giaodienhoadon giaodien = new Giaodienhoadon();
        giaodien.setSize(1024, 768);
     giaodien.setLocationRelativeTo(null);
     giaodien.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
       close();
        Thongke_chuan thok = new Thongke_chuan();
                thok.setSize(1009, 634);
                thok.setLocationRelativeTo(null);
                thok.setVisible(true);
    }//GEN-LAST:event_jMenu7MouseClicked

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        close();
        QuanLyLoaiSanPham giaodien = new QuanLyLoaiSanPham();
        giaodien.setSize(1024, 768);
     giaodien.setLocationRelativeTo(null);
     giaodien.setVisible(true);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void loaisanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loaisanphamMouseClicked
       close();
        QuanLyLoaiSanPham giaodien = new QuanLyLoaiSanPham();
        giaodien.setSize(1024, 768);
     giaodien.setLocationRelativeTo(null);
     giaodien.setVisible(true);
    }//GEN-LAST:event_loaisanphamMouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
         ho_tro giaodien = new ho_tro();
                giaodien.setSize(845, 835);
                giaodien.setLocationRelativeTo(null);
                giaodien.setVisible(true);  
    }//GEN-LAST:event_jButton13MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
         ho_tro giaodien = new ho_tro();
                giaodien.setSize(845, 835);
                giaodien.setLocationRelativeTo(null);
                giaodien.setVisible(true);  
    }//GEN-LAST:event_jMenu6MouseClicked

    private void sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanphamMouseClicked
        close();
        JFrame_sanpham giaodien;
        try {
            giaodien = new JFrame_sanpham();
            giaodien.setSize(1024, 768);
     giaodien.setLocationRelativeTo(null);
     giaodien.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GiaoDienAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_sanphamMouseClicked

    public void Showdu_lieu_ra_bang() {
        int row = ds_admin.getSelectedRow();
        String id = ds_admin.getValueAt(row, 0).toString();
//
        if (row != -1) {
            txt_ID.setText(id);
            txt_tenadmin.setText(ds_admin.getValueAt(row, 1).toString());
            txt_ngaysinh.setDate((java.util.Date) (ds_admin.getValueAt(row, 2)));
            txt_cmt.setText(ds_admin.getValueAt(row, 3).toString());
            txt_tendangnhap.setText(ds_admin.getValueAt(row, 4).toString());
            txt_matkhau.setText(ds_admin.getValueAt(row, 5).toString());
            txt_dienthoai.setText(ds_admin.getValueAt(row, 6).toString());
            txt_diachi.setText(ds_admin.getValueAt(row, 7).toString());
            combox.setSelectedItem(ds_admin.getValueAt(row, 8).toString());
        }
    }

    public void Lam_sach() {
        txt_ID.setText(null);
        txt_cmt.setText(null);
        txt_diachi.setText(null);
        txt_dienthoai.setText(null);
        txt_matkhau.setText(null);
        txt_ngaysinh.setDate(null);
        txt_tenadmin.setText(null);
        txt_tendangnhap.setText(null);
        txt_ID.setEditable(true);
        chua_nhap_ID.setText(null);
        chua_dien_mat_khau.setText(null);
        combox.setSelectedItem(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaodienquanlyAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaodienquanlyAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaodienquanlyAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaodienquanlyAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaodienquanlyAdmin giaodien = new GiaodienquanlyAdmin();
                giaodien.setSize(1120, 768);
                giaodien.setLocationRelativeTo(null);
                giaodien.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Doi_mat_khau_nut_cap_nhat;
    private javax.swing.JButton Hoadon;
    private javax.swing.JToolBar ToolBar_menu;
    private javax.swing.JLabel bang_thong_tin;
    private javax.swing.JButton buttom_timkiem;
    private javax.swing.JLabel chua_dien_mat_khau;
    private javax.swing.JLabel chua_nhap_ID;
    private javax.swing.JComboBox combox;
    private javax.swing.JButton dangky;
    private javax.swing.JLabel dialog_hinh_nen;
    private javax.swing.JButton doi_matkhau;
    private javax.swing.JDialog doimatkhau;
    private javax.swing.JTable ds_admin;
    private javax.swing.JLabel hinh_nen;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loaisanpham;
    private javax.swing.JPasswordField matkhau_hientai;
    private javax.swing.JPasswordField matkhau_moi;
    private javax.swing.JPasswordField matkhau_moi_xac_nhan;
    private javax.swing.JLabel matkhau_xac_nhan;
    private javax.swing.JButton nut_cap_nhat;
    private javax.swing.JButton nut_xoa;
    private javax.swing.JButton sanpham;
    private javax.swing.JLabel thong_bao_mk;
    private javax.swing.JLabel thongbao_mat_khau_moi;
    private javax.swing.JButton thongke;
    private javax.swing.JButton tro_giup;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_cmt;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_dienthoai;
    private javax.swing.JPasswordField txt_matkhau;
    private com.toedter.calendar.JDateChooser txt_ngaysinh;
    private javax.swing.JTextField txt_tenadmin;
    private javax.swing.JTextField txt_tendangnhap;
    private javax.swing.JTextField txt_timkiem;
    private javax.swing.JLabel xac_nhan_khongdung;
    // End of variables declaration//GEN-END:variables

}
