/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Project.View;

import Project.DAO.JDBCConnection;
import Project.DAO.TaiKhoanDao1;
import Project.Model.Taikhoan;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class TaikhoanJPanel extends javax.swing.JPanel {

    DefaultTableModel dfModel;

    /**
     * Creates new form TaikhoanJPanel
     */
    public TaikhoanJPanel() {
        initComponents();

        tblAccount.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblAccount.getTableHeader().setOpaque(false);
        tblAccount.getTableHeader().setBackground(new Color(32, 136, 203));
        tblAccount.getTableHeader().setForeground(new Color(255, 255, 255));
        tblAccount.setRowHeight(25);

        dfModel = (DefaultTableModel) tblAccount.getModel();
        dfModel.setColumnIdentifiers(new Object[]{"NAME", "PASSWORD"});

        initTable();
        //ShowTable();
        loadSinhvien();
    }

    private void initTable() {
        dfModel = new DefaultTableModel();
        dfModel.setColumnIdentifiers(new String[]{"NAME", "PASSSWORD"});
        tblAccount.setModel(dfModel);

    }

    private void loadSinhvien() {
        try {

            String sql = "select * from taikhoan";
            Connection conn = null;
            PreparedStatement pstmt = null;

            conn = JDBCConnection.getConnection();
            pstmt = conn.prepareStatement(sql);

            ResultSet rs = pstmt.executeQuery();
            dfModel.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("tendangnhap"),
                    rs.getString("matkhau")

                };
                dfModel.addRow(row);
            }
            dfModel.fireTableDataChanged();
            rs.close();
            pstmt.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccount = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAccountname = new javax.swing.JTextField();
        txtPasswordacc = new javax.swing.JPasswordField();
        txtConfirmpassword = new javax.swing.JPasswordField();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        txtSearchText = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "LIST ACCOUNT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("RussellSquare", 1, 18))); // NOI18N

        tblAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblAccount.setRowHeight(20);
        tblAccount.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAccount);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ABOUT ACCOUNT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("RussellSquare", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ACCOUNT NAME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PASSWORD ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CONFIRM PASSWORD");

        txtAccountname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAccountname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAccountnameFocusLost(evt);
            }
        });

        txtPasswordacc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPasswordacc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordaccFocusLost(evt);
            }
        });

        txtConfirmpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtConfirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmpasswordFocusLost(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\kiemtra1tiet3\\src\\main\\java\\edu\\namphan\\Project\\Images\\new-document.png")); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\kiemtra1tiet3\\src\\main\\java\\edu\\namphan\\Project\\Images\\save-file.png")); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\kiemtra1tiet3\\src\\main\\java\\edu\\namphan\\Project\\Images\\updateee.png")); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\kiemtra1tiet3\\src\\main\\java\\edu\\namphan\\Project\\Images\\delete-button.png")); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAccountname, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPasswordacc, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtConfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAccountname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPasswordacc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtConfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(35, 35, 35))
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("RussellSquare", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("QUAN LY TAI KHOAN");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray)));

        txtSearchText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\kiemtra1tiet3\\src\\main\\java\\edu\\namphan\\Project\\Images\\search.png")); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtSearchText)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearchText))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtSearchText.setText("");
        txtAccountname.setText("");
        txtPasswordacc.setText("");
        txtConfirmpassword.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txtAccountname.getText().equals("") || txtPasswordacc.getText().equals("") || txtConfirmpassword.getText().equals("")) {
            sb.append("Cần nhập thông tin đầy đủ để thêm sinh viên!");

        } else {

        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            Taikhoan taikhoan = new Taikhoan();
            taikhoan.setTendangnhap(txtAccountname.getText());
            taikhoan.setMatkhau(txtPasswordacc.getText());
            String confirm = new String(txtConfirmpassword.getPassword());
            String passsword = new String(txtPasswordacc.getPassword());
            if (passsword.equals(confirm)) {
                JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công!");
                TaiKhoanDao1 dao = new TaiKhoanDao1();
                dao.insert(taikhoan);
                loadSinhvien();
                JOptionPane.showMessageDialog(this, "Đã thêm tài khoản vào CSDL!");

            } else {
                JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không khớp! vui lòng thử lại !");
                txtConfirmpassword.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi rồi đại vương ơi !" + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtAccountnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAccountnameFocusLost
        String tendangnhap = txtAccountname.getText();
        if (tendangnhap.length() > 0) {

        } else {

            JOptionPane.showMessageDialog(this, "Tên đăng nhập không được để trống!");
        }
    }//GEN-LAST:event_txtAccountnameFocusLost

    private void txtPasswordaccFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordaccFocusLost
        String matkhau = txtPasswordacc.getText();
        if (matkhau.length() > 0) {

        } else {

            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống!");
        }
    }//GEN-LAST:event_txtPasswordaccFocusLost

    private void txtConfirmpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmpasswordFocusLost
        String xacnhan = txtConfirmpassword.getText();
        if (xacnhan.length() > 0) {

        } else {

            JOptionPane.showMessageDialog(this, "Cần xác nhận mật khẩu trước khi tạo !!");
        }
    }//GEN-LAST:event_txtConfirmpasswordFocusLost

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txtAccountname.getText().equals("") || txtPasswordacc.getText().equals("") || txtConfirmpassword.getText().equals("")) {
            sb.append("Cần nhập thông tin đầy đủ để cập nhập!");

        } else {

        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            TaiKhoanDao1 dao = new TaiKhoanDao1();
            int id = dao.FindByName(txtAccountname.getText()).getMataikhoan();
            Taikhoan tk = new Taikhoan(id, txtAccountname.getText(), txtPasswordacc.getText());
            dao.update(tk);
            loadSinhvien();
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi rồi đại vương ơi !" + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountMouseClicked
        int row = tblAccount.getSelectedRow();
        txtConfirmpassword.setText("");
        if (row >= 0) {
            Taikhoan dao = new Taikhoan();
            txtAccountname.setText(tblAccount.getValueAt(row, 0).toString());
            txtPasswordacc.setText(tblAccount.getValueAt(row, 1).toString());

        }
    }//GEN-LAST:event_tblAccountMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txtAccountname.getText().equals("")) {
            sb.append("Nhập tên tài khoản muốn xóa!");

        } else {
            txtAccountname.setBackground(Color.white);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc là muốn xóa không!") == JOptionPane.YES_OPTION) {

            try {
                TaiKhoanDao1 tkdao = new TaiKhoanDao1();
                tkdao.Delete(txtAccountname.getText());
                txtAccountname.setText("");
                txtPasswordacc.setText("");
                txtConfirmpassword.setText("");
                loadSinhvien();
                JOptionPane.showMessageDialog(this, "Đã xóa Tài khoản !");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi rồi đại vương ơi !" + e.getMessage());
            }
        } else {
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (txtSearchText.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Cần phải nhập tên tài khoản để tìm kiếm");
            return;
        }
        try {
            TaiKhoanDao1 dao = new TaiKhoanDao1();
            Taikhoan st = dao.FindByName(txtSearchText.getText());
            if (st != null) {
                txtAccountname.setText(st.getTendangnhap());
                txtPasswordacc.setText(st.getMatkhau());

            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản !");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e.getMessage());

        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblAccount;
    private javax.swing.JTextField txtAccountname;
    private javax.swing.JPasswordField txtConfirmpassword;
    private javax.swing.JPasswordField txtPasswordacc;
    private javax.swing.JTextField txtSearchText;
    // End of variables declaration//GEN-END:variables
}
