/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Connection.MySqlConnect;
import DAO.AccountDao;
import Model.Account;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class AccountView extends javax.swing.JPanel {

    private Account taikhoan = new Account();
    /**
     * Creates new form AccountView
     */
    DefaultTableModel dfModel;

    public AccountView() {
        initComponents();
        loadAcccount();
    }

    private void loadAcccount() {
        tblDanhsachtaikhoan.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tblDanhsachtaikhoan.getTableHeader().setOpaque(false);
        tblDanhsachtaikhoan.getTableHeader().setBackground(new Color(0, 153, 102));
        tblDanhsachtaikhoan.getTableHeader().setForeground(new Color(255, 255, 255));
        tblDanhsachtaikhoan.setRowHeight(25);
        dfModel = (DefaultTableModel) tblDanhsachtaikhoan.getModel();
        dfModel.setColumnIdentifiers(new Object[]{"Mã tài khoản ", "Họ và tên", "Ngày sinh", "Cmnd", "Tên đăng nhập", "SDT", "Địa chỉ", "Giới tính", "Vai trò"});
        try {
            String sql = "select * from taikhoan";
            Connection conn = null;
            PreparedStatement pstmt = null;

            conn = MySqlConnect.ConnectDb();
            pstmt = conn.prepareStatement(sql);

            ResultSet rs = pstmt.executeQuery();
            dfModel.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(11)
                };
                dfModel.addRow(row);
            }
            dfModel.fireTableDataChanged();
            rs.close();
            pstmt.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMataikhoan = new javax.swing.JTextField();
        txtHovaten = new javax.swing.JTextField();
        txtCmnd = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtMatkhau = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtTendangnhap = new javax.swing.JTextField();
        txtNgaysinh = new com.toedter.calendar.JDateChooser();
        cbbGioitinh = new javax.swing.JComboBox<>();
        cbbTinhtrang = new javax.swing.JComboBox<>();
        cbbVaitro = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        btnDangky = new com.k33ptoo.components.KButton();
        btnCapnhap = new com.k33ptoo.components.KButton();
        btnNhaplai = new com.k33ptoo.components.KButton();
        btnXoa = new com.k33ptoo.components.KButton();
        chuanhapID = new javax.swing.JLabel();
        chuanhapMK = new javax.swing.JLabel();
        chuanhapCMND = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhsachtaikhoan = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tblTimkiem = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel1.setText("Mã tài khoản:");

        jLabel2.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel2.setText("Họ và tên :");

        jLabel3.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel4.setText("Ngày sinh :");

        jLabel5.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel5.setText("Cmnd :");

        jLabel6.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel6.setText("Địa chỉ :");

        jLabel7.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel7.setText("Mật khẩu :");

        jLabel8.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel8.setText("Tên đăng nhập :");

        jLabel9.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel9.setText("SDT :");

        jLabel10.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel10.setText("Giới tính :");

        jLabel11.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel11.setText("Tình trạng :");

        jLabel12.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel12.setText("Vai trò :");

        txtMataikhoan.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N

        txtHovaten.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N

        txtCmnd.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N

        txtDiachi.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N

        txtMatkhau.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N

        txtSdt.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N

        txtTendangnhap.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N

        txtNgaysinh.setDateFormatString("yyyy-MM-dd");
        txtNgaysinh.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        cbbGioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nu", " " }));

        cbbTinhtrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hien", "an", " " }));

        cbbVaitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user", "admin", " " }));

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\QL-Laptop\\src\\icon\\edit_user_500px.png")); // NOI18N

        btnDangky.setText("Đăng ký");
        btnDangky.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDangky.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDangky.setkHoverStartColor(new java.awt.Color(0, 153, 0));
        btnDangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkyActionPerformed(evt);
            }
        });

        btnCapnhap.setText("Cập nhập ");
        btnCapnhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCapnhap.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnCapnhap.setkHoverStartColor(new java.awt.Color(0, 153, 0));
        btnCapnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhapActionPerformed(evt);
            }
        });

        btnNhaplai.setText("Nhập lại");
        btnNhaplai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNhaplai.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNhaplai.setkHoverStartColor(new java.awt.Color(0, 153, 0));
        btnNhaplai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaplaiActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setkAllowGradient(false);
        btnXoa.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        btnXoa.setkHoverColor(new java.awt.Color(255, 0, 0));
        btnXoa.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnXoa.setkHoverStartColor(new java.awt.Color(255, 0, 0));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        chuanhapID.setForeground(new java.awt.Color(255, 0, 0));

        chuanhapMK.setForeground(new java.awt.Color(255, 0, 0));

        chuanhapCMND.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chuanhapCMND, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chuanhapID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCmnd)
                                .addComponent(txtNgaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHovaten)
                                .addComponent(txtDiachi)
                                .addComponent(txtMataikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel12)
                                .addGap(74, 74, 74))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSdt)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbbGioitinh, 0, 201, Short.MAX_VALUE)
                                        .addComponent(cbbTinhtrang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbbVaitro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtTendangnhap, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                    .addComponent(txtMatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                    .addComponent(chuanhapMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnDangky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnCapnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnNhaplai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMataikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(chuanhapID, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chuanhapCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(chuanhapMK, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbbTinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbVaitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhaplai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDanhsachtaikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhsachtaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhsachtaikhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhsachtaikhoan);

        jLabel14.setFont(new java.awt.Font("SerpentineSans", 0, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 102));
        jLabel14.setText("TRANG QUẢN LÝ TÀI KHOẢN");

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel15.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel15.setText("Chi tiết Thông tin tài khoản");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(480, 480, 480))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));

        tblTimkiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblTimkiem.setText(" ");
        tblTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblTimkiemActionPerformed(evt);
            }
        });

        btnTimkiem.setBackground(new java.awt.Color(204, 255, 255));
        btnTimkiem.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnTimkiem.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\QL-Laptop\\src\\icon\\search_26px.png")); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.setPreferredSize(new java.awt.Dimension(85, 30));
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tblTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(tblTimkiem))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTimkiemActionPerformed

    private void tblDanhsachtaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhsachtaikhoanMouseClicked
        int row = tblDanhsachtaikhoan.getSelectedRow();

        if (row >= 0) {
            txtMataikhoan.setText(tblDanhsachtaikhoan.getValueAt(row, 0).toString());
            txtHovaten.setText(tblDanhsachtaikhoan.getValueAt(row, 1).toString());
            //txtNgaysinh.setDate((java.util.Date) (tblDanhsachtaikhoan.getValueAt(row, 2)));
            txtCmnd.setText(tblDanhsachtaikhoan.getValueAt(row, 3).toString());
            txtTendangnhap.setText(tblDanhsachtaikhoan.getValueAt(row, 4).toString());
            txtSdt.setText(tblDanhsachtaikhoan.getValueAt(row, 5).toString());
            txtDiachi.setText(tblDanhsachtaikhoan.getValueAt(row, 6).toString());
            cbbGioitinh.setSelectedItem(tblDanhsachtaikhoan.getValueAt(row, 7).toString());
            //cbbTinhtrang.setSelectedItem(tblDanhsachtaikhoan.getValueAt(row, 8).toString());
            cbbVaitro.setSelectedItem(tblDanhsachtaikhoan.getValueAt(row, 9).toString());
        }
    }//GEN-LAST:event_tblDanhsachtaikhoanMouseClicked
    public void DangKytaikhoan() {
        String ID = new String(txtMataikhoan.getText());
        if (ID.equals("")) {
            chuanhapID.setText("Bạn chưa nhập Mã tài khoản !");
            txtMataikhoan.requestFocus();
            return;
        }
        AccountDao nhap = new AccountDao();
        if (nhap.checkNum(this.txtMataikhoan.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Ma tai khoan bạn phải nhập số");
        }
        String tendangnhap = new String(txtTendangnhap.getText());
        if (tendangnhap.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền tên đăng nhập");
        }

        if (nhap.checkNum(this.txtCmnd.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Chứng minh thư bạn phải nhập số");
        }
//        if (txtCmnd.getText().length() >= 9) {
//            chuanhapCMND.setText("Độ dài CMND pải lớp hơn hoặc bằng 9 Số !!");
//        }
        String pw = new String(txtMatkhau.getText());
        if (pw.equals("")) {
            chuanhapMK.setText("Bạn chưa nhập mật khẩu");
            txtMatkhau.requestFocus();
            return;
        }
        if (txtMatkhau.getText().length() < 8) {
            chuanhapMK.setText("Độ dài mật khẩu pải lớp hơn hoặc bằng 8 ký tự !!");
        }

        if (nhap.checkNum(this.txtSdt.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Số điện thoại bạn phải nhập số");
        }
        String maTK = txtMataikhoan.getText();
        String tenDN = txtTendangnhap.getText();
        List<Account> listAcc = new ArrayList<>();
        listAcc = nhap.getAccount();
        for (Account taikhoan : listAcc) {
            if (taikhoan.getMataikhoan().equals(maTK)) {
                JOptionPane.showMessageDialog(null, "Mã tài khoản đã tồn tại !! vui lòng nhập lại ");

            }
            if (taikhoan.getTendangnhap().equals(tenDN)) {
                JOptionPane.showMessageDialog(null, "Tên đăng nhập đã tồn tại !! vui lòng nhập lại ");

            }
        }
        try {

            String selectdate = ((JTextField) txtNgaysinh.getDateEditor().getUiComponent()).getText();

            taikhoan.setMataikhoan(txtMataikhoan.getText());
            taikhoan.setHoten(txtHovaten.getText());
            taikhoan.setNgaysinh(selectdate);
            taikhoan.setCmnd(txtCmnd.getText());
            taikhoan.setTendangnhap(txtTendangnhap.getText());
            taikhoan.setMatkhau(txtMatkhau.getText());
            taikhoan.setDienthoai(Integer.parseInt(txtSdt.getText()));
            taikhoan.setDiachi(txtDiachi.getText());
            taikhoan.setGioitinh(cbbGioitinh.getSelectedItem().toString());
            taikhoan.setTinhtrang(cbbTinhtrang.getSelectedItem().toString());
            taikhoan.setVaitro(cbbVaitro.getSelectedItem().toString());

            AccountDao dao = new AccountDao();
            dao.insert(taikhoan);
            loadAcccount();
            JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi rồi đại vương ơi !" + e.getMessage());
        }

    }

    public void Lam_sach() {
        txtMataikhoan.setText(null);
        txtCmnd.setText(null);
        txtDiachi.setText(null);
        txtSdt.setText(null);
        txtMatkhau.setText(null);
        txtNgaysinh.setDate(null);
        txtHovaten.setText(null);
        txtTendangnhap.setText(null);
        txtMataikhoan.setEditable(true);
        chuanhapID.setText(null);
        chuanhapMK.setText(null);
        chuanhapCMND.setText(null);
        cbbGioitinh.setSelectedItem(null);
        cbbTinhtrang.setSelectedItem(null);
        cbbVaitro.setSelectedItem(null);
    }
    private void btnDangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkyActionPerformed
        DangKytaikhoan();
    }//GEN-LAST:event_btnDangkyActionPerformed

    private void btnNhaplaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaplaiActionPerformed
        Lam_sach();
    }//GEN-LAST:event_btnNhaplaiActionPerformed
    public void capnhap() {
        if (txtMataikhoan.equals("")) {
            JOptionPane.showMessageDialog(this, "Cần nhập mã tài khoản để cập nhập!");
        }
        if (txtTendangnhap.equals("")) {
            JOptionPane.showMessageDialog(this, "Cần nhập tên đăng nhập để cập nhập");
        }
        if (txtMatkhau.equals("")) {
            JOptionPane.showMessageDialog(this, "Cần nhập Mật khẩu  để cập nhập");
        }
        try {
            String selectdate = ((JTextField) txtNgaysinh.getDateEditor().getUiComponent()).getText();
            AccountDao daoo = new AccountDao();
            String id = daoo.FindByID(txtMataikhoan.getText()).getMataikhoan();
            Account account = new Account(
                    id,
                    txtHovaten.getText(),
                    selectdate,
                    txtCmnd.getText(),
                    txtTendangnhap.getText(),
                    txtMatkhau.getText(),
                    Integer.parseInt(txtSdt.getText()),
                    txtDiachi.getText(),
                    cbbGioitinh.getSelectedItem().toString(),
                    cbbTinhtrang.getSelectedItem().toString(),
                    cbbVaitro.getSelectedItem().toString()
            );
            daoo.update(account);
            loadAcccount();
            JOptionPane.showMessageDialog(this, "Đã cập nhập thành công!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi rồi đại vương ơi !" + e.getMessage());
        }

    }
    private void btnCapnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhapActionPerformed
        capnhap();

    }//GEN-LAST:event_btnCapnhapActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        if (tblTimkiem.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Cần phải nhập tên tài khoản để tìm kiếm");
            return;
        }
        try {
            AccountDao dao = new AccountDao();
            Account account = dao.FindByID(tblTimkiem.getText());
            if (account != null) {
                txtMataikhoan.setText(account.getMataikhoan());
                txtHovaten.setText(account.getHoten());
                //txtNgaysinh.setText(account.getMatkhau());
                txtCmnd.setText(account.getCmnd());
                txtDiachi.setText(account.getDiachi());
                txtTendangnhap.setText(account.getMatkhau());
                txtMatkhau.setText(account.getMatkhau());
                //txtSdt.setText(Integer.parseInt(account.getDienthoai()));

            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản !");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e.getMessage());

        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb = new StringBuilder();

        if (txtMataikhoan.getText().equals("")) {
            sb.append("Nhập tên sinh viên muốn xóa!");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc là muốn xóa không!") == JOptionPane.YES_OPTION) {

            try {
                AccountDao dao = new AccountDao();
                dao.Delete(txtMataikhoan.getText());
                loadAcccount();
                JOptionPane.showMessageDialog(this, "Đã xóa sinh viên !");
                Lam_sach();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi rồi đại vương ơi !" + e.getMessage());
            }
        } else {
            return;
        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnCapnhap;
    private com.k33ptoo.components.KButton btnDangky;
    private com.k33ptoo.components.KButton btnNhaplai;
    private javax.swing.JButton btnTimkiem;
    private com.k33ptoo.components.KButton btnXoa;
    private javax.swing.JComboBox<String> cbbGioitinh;
    private javax.swing.JComboBox<String> cbbTinhtrang;
    private javax.swing.JComboBox<String> cbbVaitro;
    private javax.swing.JLabel chuanhapCMND;
    private javax.swing.JLabel chuanhapID;
    private javax.swing.JLabel chuanhapMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhsachtaikhoan;
    private javax.swing.JTextField tblTimkiem;
    private javax.swing.JTextField txtCmnd;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtHovaten;
    private javax.swing.JTextField txtMataikhoan;
    private javax.swing.JTextField txtMatkhau;
    private com.toedter.calendar.JDateChooser txtNgaysinh;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTendangnhap;
    // End of variables declaration//GEN-END:variables
}
