/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connection.MySqlConnect;
import DAO.AccountDao;
import Model.Account;
import com.toedter.calendar.JDateChooser;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import quanlylaptop.GiaodienquanlyAdmin;

/**
 *
 * @author Tai
 */
public class LoginView extends javax.swing.JFrame {
 private Account taikhoan = new Account();
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public JTextField getCmt() {
        return txtCmnd;
    }

    public JButton getDang_ky() {
        return dang_ky;
    }

    public JDialog getDangky() {
        return dangky;
    }

    public JTextField getDia_chi_hep() {
        return txtDiachi;
    }

    public JTextField getDien_thoai() {
        return txtSdt;
    }

    

    public JComboBox getGioitinh() {
        return cbbGioitinh;
    }

    public JTextField getHoten() {
        return txtHovaten;
    }

    public JLabel getLoi_mat_khau() {
        return loi_mat_khau;
    }

    public JTextField getMaadmin_txt() {
        return txtMataikhoan;
    }

    public JPasswordField getMatkhau_dangky_o_dialog() {
        return txtMatkhau;
    }

    public JDateChooser getNgaythang() {
        return txtNgaysinh;
    }

    public JLabel getNhap_matkhau() {
        return nhap_matkhau;
    }

    public JButton getNut_dang_ky() {
        return nut_dang_ky;
    }

    public JButton getNut_dang_nhap() {
        return nut_dang_nhap;
    }

    public JTextField getTen_dang_nhap() {
        return txtTendangnhap;
    }

    public JTextField getTxt_tendangnhap() {
        return txt_tendangnhap;
    }

     

    public JPasswordField getTxt_matkhau() {
        return txt_matkhau;
    }

    public JLabel getJblMess() {
        return jblMess;
    }


    // làm sạch thông tin ở khung sau khi insert, sản phẩm, tài khoản,....
    public void Lam_sach() {
        txtHovaten.setText(null);
        txtTendangnhap.setText(null);
        txtMatkhau.setText(null); 
        txtNgaysinh.setDate(null);
    }

    public LoginView() {
        initComponents();
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dangky = new javax.swing.JDialog();
        txtMataikhoan = new javax.swing.JTextField();
        cbbGioitinh = new javax.swing.JComboBox();
        txtCmnd = new javax.swing.JTextField();
        txtNgaysinh = new com.toedter.calendar.JDateChooser();
        nhap_matkhau = new javax.swing.JLabel();
        txtHovaten = new javax.swing.JTextField();
        txtTendangnhap = new javax.swing.JTextField();
        dang_ky = new javax.swing.JButton();
        txtMatkhau = new javax.swing.JPasswordField();
        loi_mat_khau = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbbTinhtrang = new javax.swing.JComboBox<>();
        cbbVaitro = new javax.swing.JComboBox<>();
        chuanhapID = new javax.swing.JLabel();
        chuanhapMK = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_tendangnhap = new javax.swing.JTextField();
        txt_matkhau = new javax.swing.JPasswordField();
        nut_dang_nhap = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nut_dang_ky = new com.k33ptoo.components.KButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jblMess = new javax.swing.JLabel();

        dangky.setTitle("From Đăng Ký Tài Khoản");
        dangky.setResizable(false);
        dangky.getContentPane().setLayout(null);

        txtMataikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMataikhoanActionPerformed(evt);
            }
        });
        dangky.getContentPane().add(txtMataikhoan);
        txtMataikhoan.setBounds(140, 90, 120, 30);

        cbbGioitinh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbbGioitinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nu", "Gay", "Less" }));
        dangky.getContentPane().add(cbbGioitinh);
        cbbGioitinh.setBounds(110, 550, 210, 30);

        txtCmnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmndActionPerformed(evt);
            }
        });
        dangky.getContentPane().add(txtCmnd);
        txtCmnd.setBounds(140, 240, 180, 30);

        txtNgaysinh.setDateFormatString("yyyy-MM-dd");
        txtNgaysinh.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dangky.getContentPane().add(txtNgaysinh);
        txtNgaysinh.setBounds(140, 190, 180, 30);

        nhap_matkhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nhap_matkhau.setForeground(new java.awt.Color(255, 0, 51));
        dangky.getContentPane().add(nhap_matkhau);
        nhap_matkhau.setBounds(190, 430, 180, 20);

        txtHovaten.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtHovaten.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dangky.getContentPane().add(txtHovaten);
        txtHovaten.setBounds(140, 140, 180, 28);

        txtTendangnhap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTendangnhap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dangky.getContentPane().add(txtTendangnhap);
        txtTendangnhap.setBounds(140, 290, 180, 30);

        dang_ky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dialog/anh-dk.png"))); // NOI18N
        dang_ky.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dang_ky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dang_kyActionPerformed(evt);
            }
        });
        dangky.getContentPane().add(dang_ky);
        dang_ky.setBounds(110, 710, 112, 56);

        txtMatkhau.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMatkhau.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dangky.getContentPane().add(txtMatkhau);
        txtMatkhau.setBounds(140, 340, 180, 30);
        dangky.getContentPane().add(loi_mat_khau);
        loi_mat_khau.setBounds(590, 420, 190, 20);

        txtSdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSdtActionPerformed(evt);
            }
        });
        dangky.getContentPane().add(txtSdt);
        txtSdt.setBounds(140, 400, 180, 30);
        dangky.getContentPane().add(txtDiachi);
        txtDiachi.setBounds(100, 450, 220, 70);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Họ tên :");
        dangky.getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 140, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tên đăng nhập");
        dangky.getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 300, 130, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mật khẩu :");
        dangky.getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 350, 90, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Ngày tháng :");
        dangky.getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 190, 110, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Mã tài khoản: ");
        dangky.getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 90, 110, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Điện thoại :");
        dangky.getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 410, 90, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Giới tính :");
        dangky.getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 560, 80, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Địa chỉ :");
        dangky.getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 470, 54, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CMND :");
        dangky.getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 250, 60, 17);

        kButton1.setText("Dang ky");
        kButton1.setFont(new java.awt.Font("VnBodoni2", 1, 18)); // NOI18N
        dangky.getContentPane().add(kButton1);
        kButton1.setBounds(0, 5, 450, 70);

        jLabel16.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel16.setText("Tình trạng :");
        dangky.getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 620, 85, 13);

        jLabel17.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel17.setText("Vai trò :");
        dangky.getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 660, 58, 13);

        cbbTinhtrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hien", "an", " " }));
        dangky.getContentPane().add(cbbTinhtrang);
        cbbTinhtrang.setBounds(150, 600, 51, 22);

        cbbVaitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user", "admin", " " }));
        dangky.getContentPane().add(cbbVaitro);
        cbbVaitro.setBounds(150, 650, 62, 22);
        dangky.getContentPane().add(chuanhapID);
        chuanhapID.setBounds(260, 100, 150, 0);
        dangky.getContentPane().add(chuanhapMK);
        chuanhapMK.setBounds(140, 380, 240, 0);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        kGradientPanel1.setForeground(new java.awt.Color(102, 255, 0));
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(51, 255, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 255));

        kGradientPanel2.setkBorderRadius(20);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("SerpentineSans", 1, 30)); // NOI18N
        jLabel1.setText("Login form");

        txt_tendangnhap.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_tendangnhap.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_matkhau.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_matkhau.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nut_dang_nhap.setBorder(null);
        nut_dang_nhap.setText("Login");
        nut_dang_nhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nut_dang_nhap.setkBorderRadius(40);
        nut_dang_nhap.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        nut_dang_nhap.setkHoverStartColor(new java.awt.Color(51, 153, 0));
        nut_dang_nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut_dang_nhapActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\QL-Laptop\\src\\icon\\undraw500.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\QL-Laptop\\src\\icon\\user_50px.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\QL-Laptop\\src\\icon\\password_64px.png")); // NOI18N

        nut_dang_ky.setText("Create new account");
        nut_dang_ky.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nut_dang_ky.setkBorderRadius(0);
        nut_dang_ky.setkHoverStartColor(new java.awt.Color(102, 255, 102));
        nut_dang_ky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut_dang_kyActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("or");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nut_dang_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(42, 42, 42)))))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(nut_dang_ky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblMess, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(136, 136, 136))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(txt_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(nut_dang_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nut_dang_ky, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblMess, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //  conn = MySqlConnect.ConnectDb();
    }//GEN-LAST:event_formWindowActivated

    private void dang_kyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dang_kyActionPerformed
        
       DangKytaikhoan();
    }//GEN-LAST:event_dang_kyActionPerformed
 public void DangKytaikhoan() {
        String ID = new String(txtMataikhoan.getText());
        if (ID.equals("")) {
            chuanhapID.setText("Bạn chưa nhập Mã tài khoản !");
            txtMataikhoan.requestFocus();
            return;
        }
        AccountDao nhap = new AccountDao();
        if (nhap.checkNum(this.txtMataikhoan.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Ma tai khoan bạn phải nhập số");
        }
        String tendangnhap = new String(txtTendangnhap.getText());
        if (tendangnhap.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền tên đăng nhập");
        }

        if (nhap.checkNum(this.txtCmnd.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Chứng minh thư bạn phải nhập số");
        }
//        if (txtCmnd.getText().length() >= 9) {
//            chuanhapCMND.setText("Độ dài CMND pải lớp hơn hoặc bằng 9 Số !!");
//        }
        String pw = new String(txtMatkhau.getText());
        if (pw.equals("")) {
            chuanhapMK.setText("Bạn chưa nhập mật khẩu");
            txtMatkhau.requestFocus();
            return;
        }
        if (txtMatkhau.getText().length() < 8) {
            chuanhapMK.setText("Độ dài mật khẩu pải lớp hơn hoặc bằng 8 ký tự !!");
        }

        if (nhap.checkNum(this.txtSdt.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Số điện thoại bạn phải nhập số");
        }
        String maTK = txtMataikhoan.getText();
        String tenDN = txtTendangnhap.getText();
        java.util.List<Account> listAcc = new ArrayList<>();
        listAcc = nhap.getAccount();
        for (Account taikhoan : listAcc) {
            if (taikhoan.getMataikhoan().equals(maTK)) {
                JOptionPane.showMessageDialog(null, "Mã tài khoản đã tồn tại !! vui lòng nhập lại ");

            }
            if (taikhoan.getTendangnhap().equals(tenDN)) {
                JOptionPane.showMessageDialog(null, "Tên đăng nhập đã tồn tại !! vui lòng nhập lại ");

            }
        }
        try {

            String selectdate = ((JTextField) txtNgaysinh.getDateEditor().getUiComponent()).getText();

            taikhoan.setMataikhoan(txtMataikhoan.getText());
            taikhoan.setHoten(txtHovaten.getText());
            taikhoan.setNgaysinh(selectdate);
            taikhoan.setCmnd(txtCmnd.getText());
            taikhoan.setTendangnhap(txtTendangnhap.getText());
            taikhoan.setMatkhau(txtMatkhau.getText());
            taikhoan.setDienthoai(Integer.parseInt(txtSdt.getText()));
            taikhoan.setDiachi(txtDiachi.getText());
            taikhoan.setGioitinh(cbbGioitinh.getSelectedItem().toString());
            taikhoan.setTinhtrang(cbbTinhtrang.getSelectedItem().toString());
            taikhoan.setVaitro(cbbVaitro.getSelectedItem().toString());

            AccountDao dao = new AccountDao();
            dao.insert(taikhoan); 
            JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi rồi đại vương ơi !" + e.getMessage());
        }

    }
    private void nut_dang_nhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_dang_nhapActionPerformed

    }//GEN-LAST:event_nut_dang_nhapActionPerformed

    private void nut_dang_kyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_dang_kyActionPerformed
        dangky.setSize(450, 784);
        dangky.setLocationRelativeTo(null);
        dangky.setVisible(true);
    }//GEN-LAST:event_nut_dang_kyActionPerformed

    private void txtSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSdtActionPerformed

    private void txtMataikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMataikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMataikhoanActionPerformed

    private void txtCmndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCmndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginView giaodien = new LoginView();
                giaodien.setSize(1024, 768);
                giaodien.setLocationRelativeTo(null);
                giaodien.setVisible(true);
//                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbGioitinh;
    private javax.swing.JComboBox<String> cbbTinhtrang;
    private javax.swing.JComboBox<String> cbbVaitro;
    private javax.swing.JLabel chuanhapID;
    private javax.swing.JLabel chuanhapMK;
    private javax.swing.JButton dang_ky;
    private javax.swing.JDialog dangky;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jblMess;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel loi_mat_khau;
    private javax.swing.JLabel nhap_matkhau;
    private com.k33ptoo.components.KButton nut_dang_ky;
    private com.k33ptoo.components.KButton nut_dang_nhap;
    private javax.swing.JTextField txtCmnd;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtHovaten;
    private javax.swing.JTextField txtMataikhoan;
    private javax.swing.JPasswordField txtMatkhau;
    private com.toedter.calendar.JDateChooser txtNgaysinh;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTendangnhap;
    private javax.swing.JPasswordField txt_matkhau;
    private javax.swing.JTextField txt_tendangnhap;
    // End of variables declaration//GEN-END:variables
}
