/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Connection.MySqlConnect;
import Controller.ProductController;
import DAO.CategoryDao;
import DAO.ProductDao;
import static Iteam.UpdateTable.con;
import Model.Category;
import Model.Product;
import com.k33ptoo.components.KButton;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jfree.ui.tabbedui.RootPanel;

/**
 *
 * @author ADMIN
 */
public class ProductView extends javax.swing.JPanel {

    DefaultTableModel dfModel;
    private ProductDao prDao = new ProductDao();
    ProductView view;
    Connection conn;
    ResultSet rs;
    PreparedStatement pstmt;

    public ProductView() {
        initComponents();
        loadProduct();
        setComboxCategory();
    }

    public KButton getBtnCapnhap() {
        return btnCapnhap;
    }

    public KButton getBtnThemsp() {
        return btnThemsp;
    }

    public JButton getBtnTimkiem() {
        return btnTimkiem;
    }

    public KButton getBtnXoa() {
        return btnXoa;
    }

    public JComboBox<String> getCbbBaohanh() {
        return cbbBaohanh;
    }

    public JComboBox<String> getCbbLinhkien() {
        return cbbLinhkien;
    }

    public JComboBox<Category> getCbbLoaisp() {
        return cbbLoaisp2;
    } 
    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JPanel getjPanel9() {
        return jPanel9;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getTbl_danhsachsanpham() {
        return tbl_danhsachsanpham;
    }

    public JTextField getTxtBaiviet() {
        return txtBaiviet;
    }

    public JTextField getTxtGiasp() {
        return txtGiasp;
    }

    public JTextField getTxtKhuyenmai() {
        return txtKhuyenmai;
    }

    public JTextField getTxtMasp() {
        return txtMasp;
    }

    public JTextField getTxtSoluongsp() {
        return txtSoluongsp;
    }

    public JTextField getTxtTensp() {
        return txtTensp;
    }

    public JTextField getTxtThongso() {
        return txtThongso;
    }

    public JTextField getTxtTimkiem() {
        return txtTimkiem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMasp = new javax.swing.JTextField();
        txtTensp = new javax.swing.JTextField();
        txtGiasp = new javax.swing.JTextField();
        txtSoluongsp = new javax.swing.JTextField();
        txtBaiviet = new javax.swing.JTextField();
        txtKhuyenmai = new javax.swing.JTextField();
        txtThongso = new javax.swing.JTextField();
        cbbLinhkien = new javax.swing.JComboBox<>();
        cbbBaohanh = new javax.swing.JComboBox<>();
        btnThemsp = new com.k33ptoo.components.KButton();
        btnCapnhap = new com.k33ptoo.components.KButton();
        btnXoa = new com.k33ptoo.components.KButton();
        jLabel13 = new javax.swing.JLabel();
        txtTomtac = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTinhtrang = new javax.swing.JTextField();
        cbb11 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cbbLoaisp2 = new javax.swing.JComboBox<>();
        txtTimkiem = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        XuatExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhsachsanpham = new javax.swing.JTable();

        jLabel5.setFont(new java.awt.Font("SerpentineSans", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 102));
        jLabel5.setText("TRANG QUẢN LÝ SẢN PHẨM");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel1.setText("Chi tiết Thông tin sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(480, 480, 480))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(0, 153, 102));

        jLabel2.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("Mã Sản Phẩm :");

        jLabel3.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("Tên Sản Phẩm :");

        jLabel4.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("Giá Sản Phẩm :");

        jLabel6.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 102));
        jLabel6.setText("Số Lượng :");

        jLabel7.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 102));
        jLabel7.setText("Bài Viết :");

        jLabel8.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8.setText("Linh Kiện kèm Theo");

        jLabel9.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 102));
        jLabel9.setText("Loại Sản Phẩm :");

        jLabel10.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 102));
        jLabel10.setText("Bảo Hành :");

        jLabel11.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 102));
        jLabel11.setText("Khuyến Mại :");

        jLabel12.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 102));
        jLabel12.setText("Thông Số :");

        txtSoluongsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoluongspActionPerformed(evt);
            }
        });

        cbbLinhkien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuột ", "Phím ", "Chuột ", "Tai nghe " }));
        cbbLinhkien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLinhkienActionPerformed(evt);
            }
        });

        cbbBaohanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "24", "36", "48" }));

        btnThemsp.setText("Thêm sản phẩm ");
        btnThemsp.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThemsp.setkBorderRadius(30);
        btnThemsp.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnThemsp.setkHoverStartColor(new java.awt.Color(51, 153, 0));
        btnThemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemspActionPerformed(evt);
            }
        });

        btnCapnhap.setText("Cập Nhập");
        btnCapnhap.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnCapnhap.setkBorderRadius(30);
        btnCapnhap.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnCapnhap.setkHoverStartColor(new java.awt.Color(51, 153, 0));

        btnXoa.setText("Xóa");
        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXoa.setkBackGroundColor(new java.awt.Color(255, 102, 102));
        btnXoa.setkBorderRadius(30);
        btnXoa.setkEndColor(new java.awt.Color(255, 51, 51));
        btnXoa.setkHoverEndColor(new java.awt.Color(255, 51, 51));
        btnXoa.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnXoa.setkHoverStartColor(new java.awt.Color(255, 51, 0));
        btnXoa.setkStartColor(new java.awt.Color(255, 51, 51));

        jLabel13.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 102));
        jLabel13.setText("Tóm tắc");

        jLabel14.setFont(new java.awt.Font("RussellSquare", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 102));
        jLabel14.setText("Tình trạng");

        cbb11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel6)))
                                .addGap(18, 18, 18)
                                .addComponent(txtSoluongsp, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtGiasp, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTensp))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtBaiviet, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTomtac)))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtThongso, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtTinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(35, 35, 35)
                            .addComponent(cbbBaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbbLinhkien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbb11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnThemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(cbbLinhkien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cbb11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiasp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbbBaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoluongsp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(txtKhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtThongso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBaiviet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCapnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTomtac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 153, 102));

        jLabel18.setFont(new java.awt.Font("RussellSquare", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Loại sản phẩm :");

        cbbLoaisp2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbbLoaisp2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbbLoaisp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaisp2ActionPerformed(evt);
            }
        });

        txtTimkiem.setPreferredSize(new java.awt.Dimension(69, 30));

        btnTimkiem.setBackground(new java.awt.Color(204, 255, 255));
        btnTimkiem.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnTimkiem.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\QL-Laptop\\src\\icon\\search_26px.png")); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.setPreferredSize(new java.awt.Dimension(85, 30));

        XuatExcel.setText("Xuất File Excel");
        XuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XuatExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbLoaisp2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(XuatExcel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbbLoaisp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(XuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbl_danhsachsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_danhsachsanpham.setInheritsPopupMenu(true);
        tbl_danhsachsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_danhsachsanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_danhsachsanpham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(813, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoluongspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoluongspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoluongspActionPerformed

    public void setComboxCategory() {
        List<Category> categories = CategoryDao.findAll();
        categories.forEach(item -> {
            //cbbLoaisp1.addItem(item);
            cbbLoaisp2.addItem(item);
        });
    }

    private void btnThemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemspActionPerformed
        if (this.getTxtMasp().getText().length() == 0) {
            JOptionPane.showMessageDialog(btnCapnhap, "Mã sản phẩm không được để trống", "Thông báo", 1);
        } else if (this.getTxtMasp().getText().length() > 6) {
            JOptionPane.showMessageDialog(btnCapnhap, "Mã sản phẩm vượt quá 6 ký tự", "Thông báo", 1);
        } else if (this.getTxtTensp().getText().length() == 0) {
            JOptionPane.showMessageDialog(btnCapnhap, "Tên sản phẩm không được để trống", "Thông báo", 1);
        } else if (this.getTxtTensp().getText().length() > 70) {
            JOptionPane.showMessageDialog(btnCapnhap, "Tên sản phẩm vượt quá 70 ký tự", "Thông báo", 1);
        } else if (this.getTxtSoluongsp().getText().length() == 0) {
            JOptionPane.showMessageDialog(btnCapnhap, "Số lượng sản phẩm không được để trống", "Thông báo", 1);
        } else {
            try {
                Product product = new Product();
                product.setMasp(Integer.parseInt(txtMasp.getText()));
                product.setLoaisp(String.valueOf(cbb11.getSelectedItem()));
                product.setTensp(txtTensp.getText());
                product.setGia(Double.parseDouble(txtGiasp.getText()));
                product.setTomtac(txtTomtac.getText());
                product.setLinhkien(cbbLinhkien.getSelectedItem().toString());
                product.setKhuyenmai(txtKhuyenmai.getText());
                product.setThongso(txtThongso.getText());
                product.setBaiviet(txtBaiviet.getText()); 
                product.setBaohanh(Integer.parseInt(cbbBaohanh.getSelectedItem().toString()));
                product.setSoluong(Integer.parseInt(txtSoluongsp.getText()));
                product.setTinhtrang(txtTinhtrang.getText());
                ProductDao productdao = new ProductDao();

                productdao.themSP(product);loadProduct();
                JOptionPane.showMessageDialog(btnCapnhap, "Đã thêm  sản phẩm " + product.getTensp() + "  ", " Thông báo", 1);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(btnCapnhap, "Lỗi rồi " + " ", "Thông báo", 1);
            }

        }
//JOptionPane.showMessageDialog(btnCapnhap, String.valueOf(cbb11.getSelectedItem()));
    }//GEN-LAST:event_btnThemspActionPerformed
    private void loadProduct() {
        tbl_danhsachsanpham.getTableHeader().setFont(new Font("RussellSquare", Font.BOLD, 16));
        tbl_danhsachsanpham.getTableHeader().setOpaque(false);
        tbl_danhsachsanpham.getTableHeader().setBackground(new Color(0, 153, 102));
        tbl_danhsachsanpham.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl_danhsachsanpham.setRowHeight(30);
        dfModel = (DefaultTableModel) tbl_danhsachsanpham.getModel();
        dfModel.setColumnIdentifiers(new Object[]{
            "MaSP", "LoaiSp", "TenSP", "GiaSP", "Linhkien", "Khuyenmai", "Thongso", "Baiviet", "Baohanh", "Soluong"});
        try {
            String sql = "select * from sanpham";
            Connection conn = null;
            PreparedStatement pstmt = null;

            conn = MySqlConnect.ConnectDb();
            pstmt = conn.prepareStatement(sql);

            ResultSet rs = pstmt.executeQuery();
            dfModel.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10),
                    rs.getString(11),};
                dfModel.addRow(row);
            }
            dfModel.fireTableDataChanged();
            rs.close();
            pstmt.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }
    private void cbbLinhkienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLinhkienActionPerformed

    }//GEN-LAST:event_cbbLinhkienActionPerformed

    private void tbl_danhsachsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhsachsanphamMouseClicked

        int row = tbl_danhsachsanpham.getSelectedRow();

        if (row >= 0) {
            txtMasp.setText(tbl_danhsachsanpham.getValueAt(row, 0).toString());
            cbb11.setSelectedItem(tbl_danhsachsanpham.getValueAt(row, 1).toString());
            txtTensp.setText(tbl_danhsachsanpham.getValueAt(row, 2).toString());
            txtGiasp.setText(tbl_danhsachsanpham.getValueAt(row, 3).toString());
            cbbLinhkien.setSelectedItem(tbl_danhsachsanpham.getValueAt(row, 4).toString());
            txtKhuyenmai.setText(tbl_danhsachsanpham.getValueAt(row, 5).toString());
            txtThongso.setText(tbl_danhsachsanpham.getValueAt(row, 6).toString());
            txtBaiviet.setText(tbl_danhsachsanpham.getValueAt(row, 7).toString());
            cbbBaohanh.setSelectedItem(tbl_danhsachsanpham.getValueAt(row, 8));
            txtSoluongsp.setText(tbl_danhsachsanpham.getValueAt(row, 9).toString());
        }
    }//GEN-LAST:event_tbl_danhsachsanphamMouseClicked

    private void XuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XuatExcelActionPerformed
        ProductController ctl = new ProductController();
        ctl.xuatFileExcel();
    }//GEN-LAST:event_XuatExcelActionPerformed

    private void cbbLoaisp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaisp2ActionPerformed
// String masp;       
//try {
//            int row = this.tbDanhsachsanpham.getSelectedRow();
//            String idrow = this.tb_danhsachsanpham.getModel().getValueAt(row, 0).toString();
//            String sql1 = "SELECT * FROM `sanpham` WHERE masp='" + idrow + "'";
//            ResultSet rs = UpdateTable.ShowTextField(sql1);
//            if (rs.next()) {
//                masp = rs.getString("masp");
//                this.txtMasp.setText(rs.getString("masp")); 
//                this.txtTensp.setText(rs.getString("tensp"));
//                this.txtGiasp.setText(rs.getString("gia"));
//                this.cbbLinhkien.setSelectedItem(rs.getString("linhkien"));
//                this.txtKhuyenmai.setText(rs.getString("khuyenmai"));
//                this.txtThongso.setText(rs.getString("thongso"));
//                this.txtBaiviet.setText(rs.getString("baiviet"));
//                this.cbbBaohanh.setSelectedItem(rs.getString("baohanh"));
//                this.txtSoluongsp.setText(rs.getString("soluong"));
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e, "Thông báo lỗi", 1);
//        }
    }//GEN-LAST:event_cbbLoaisp2ActionPerformed

    private void cbbLoaisp2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbbLoaisp2PopupMenuWillBecomeInvisible
          String manew = "";
String sql = "SELECT `malsp` FROM `loaisanpham` WHERE `tenlsp`= ?";
        try {
             pstmt = con.prepareStatement(sql);
            pstmt.setString(1, this.cbbLoaisp2.getSelectedItem().toString()); 
            rs = pstmt.executeQuery(); 
            while (rs.next()) {
                manew = rs.getString("malsp"); 
            }
        } catch (SQLException ex) {
                    }
    }//GEN-LAST:event_cbbLoaisp2PopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XuatExcel;
    private com.k33ptoo.components.KButton btnCapnhap;
    private com.k33ptoo.components.KButton btnThemsp;
    private javax.swing.JButton btnTimkiem;
    private com.k33ptoo.components.KButton btnXoa;
    private javax.swing.JComboBox<String> cbb11;
    private javax.swing.JComboBox<String> cbbBaohanh;
    private javax.swing.JComboBox<String> cbbLinhkien;
    private javax.swing.JComboBox<Category> cbbLoaisp2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_danhsachsanpham;
    private javax.swing.JTextField txtBaiviet;
    private javax.swing.JTextField txtGiasp;
    private javax.swing.JTextField txtKhuyenmai;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtSoluongsp;
    private javax.swing.JTextField txtTensp;
    private javax.swing.JTextField txtThongso;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JTextField txtTinhtrang;
    private javax.swing.JTextField txtTomtac;
    // End of variables declaration//GEN-END:variables
}
